# Generated by Django 4.1 on 2025-11-23 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mysite", "0002_apply_job_experience_alter_postjob_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="apply_job",
            name="cgpa",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="apply_job",
            name="college",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AddField(
            model_name="apply_job",
            name="experience_years",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="apply_job",
            name="similarity_score",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="apply_job",
            name="skills",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="postjob",
            name="min_cgpa",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="postjob",
            name="min_experience",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="postjob",
            name="required_skills",
            field=models.TextField(default="", help_text="Comma-separated skills"),
        ),
    ]
