# Generated by Django 4.2.1 on 2025-11-24 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mysite", "0003_apply_job_cgpa_apply_job_college_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="postjob",
            name="job_code",
            field=models.CharField(blank=True, max_length=3, null=True, unique=True),
        ),
    ]
