# Generated by Django 4.2.1 on 2025-12-02 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mysite", "0004_postjob_job_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="apply_job",
            name="parsed_text",
            field=models.TextField(blank=True, default=""),
        ),
    ]
